apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gameclient
  name: gameclient
  namespace: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameclient
  template:
    metadata:
      labels:
        app: gameclient
    spec:
      containers:
      - name: gameclient
        image: quay.io/burrsutter/balloon-game-client:1.0.3
        ports:
          - containerPort: 8080
